### ISSUE TITLE
2019.46.4.0 - Can no longer fullsize a player 

### ISSUE THREAD

**Issue by Kumasasa** [NateMccomb/TeslaCamViewerII#8]
right-double-click on a camera does nothing.

**Comment by NateMccomb** [comment]
This is a similar bug as issue #7. The VLC players are not creating all the controls properly when a folder is first loaded or at random intervals. If you left click on each player you should be able to move it and right clicking should allow you to resize that corner but if this doesn't work then this is a sign of it not working properly. When the VLC players can't be adjusted with the mouse then those same players will have issues if the playback speed is set to 3-5x and they will be the ones that cause the whole viewer to crash. If you change to a different time within an event then that seems to help but not always fix the issue. 

I was able to test the issue when the folder is first loaded by removing the quick start feature were the files would start playing before they are all done being analyzed but that didn't solve the issue of it randomly happening and causing the viewer to crash. So I'm leaving that feature in for the moment so that load speeds are similar to the original TeslaCam Viewer (as a requested feature) but still trying to figure out what is causing this bug. I have uploaded the source code for 2019.46.4.0 if anyone wants dig in.

**Comment by NateMccomb** [comment]
It still seams the moving or resizing players has an issue or you could just look at it as a new feature. To resize or move a player first manually select a different time under "Selected Event" and now the features will be enabled otherwise the players will not detect the mouse click. I'm still not sure why this is yet!

**Comment by Kumasasa** [comment]
Moving / Resizing the  players work, but the original isssue "Cannot fullsize a player with double right-click" is still present.

**Comment by NateMccomb** [comment]
I'll work on adding this in the next release. VLC doesn't support a Double Click event, only a single so I'll have to program this logic manually but shouldn't be a big issue.

**Comment by NateMccomb** [comment]
I have fixed the issues with making the player full size for both WMP and VLC but VLC still requires you to change the "Selected Event" time before they all have their controls become enabled. I'm still unsure how to resolve the VLC controls issue where a "Selected Event" change is needed before the players respond to mouse events. Let me know if 2019.52.0.0 fixed the Full Size player issue for you.

**Comment by Kumasasa** [comment]
Sorry for the late answer.
It's in fact working as described now.
