### ISSUE TITLE
Consider targeting .NET 4.x

### ISSUE THREAD

**Issue by BrandonLive** [NateMccomb/TeslaCamViewerII#9]
The current project targets .NET 3.x which is quite old, and not installed by default in Windows 10 (or 8.x for that matter). Building against .NET 4.x would ease the install process for most users and help those of us who want to avoid the overhead of installing and updating the old 3.x framework.

**Comment by NateMccomb** [comment]
I just switched TeslaCam Viewer II 2019.46.6.1 to .NET 4.5 instead of 3.5. Try it out and let me know if you have any issues. 
I guess .NET 3.5 could be a bit of a headache for some and like you said 4.5 or newer seems to come default now on Windows 8 & 10. We'll see if this produces any new bugs or issues for current users.

**Comment by Kumasasa** [comment]
No issues found so far.

**Comment by Kumasasa** [comment]
Got some crashes while moving the playback time marker, but that can be a VLC issue

**Comment by BrandonLive** [comment]
Working great! Thanks for addressing this so quickly!
